name: Build kernel debs

on:
  workflow_dispatch:
  
jobs:
  build-kernel-debs:
    runs-on: ubuntu-latest
    container:
      image: aterfax/relaxable-rmrr-proxmox-kernel-builder:latest
      options: -v ${{ github.workspace }}:/build/proxmox/proxmox-kernel
        
    steps:          
    - name: Zip up debs
      run: zip release.zip ${{ github.workspace }}/debs -r

    - name: Archive the generated debs
      uses: actions/upload-artifact@v3
      with:
        name: RMRR-Relaxation-Patched-PVE-kernel-debs-zip
        path: release.zip
